"""Typed error hierarchy.

Every class derives from RuntimeError so existing `except RuntimeError`
call sites keep working; the CLI maps YtDistillError to a clean one-line
message + exit 1, while unexpected exceptions still traceback (bugs should
be loud).
"""
from __future__ import annotations


class YtDistillError(RuntimeError):
    """Base for all predictable pipeline failures."""


class TranscriptError(YtDistillError): ...
class ExtractError(YtDistillError): ...
class DistillError(YtDistillError): ...
class CitationError(YtDistillError): ...
class RefFollowError(YtDistillError): ...
class LLMError(YtDistillError): ...
class ModelConfigError(YtDistillError): ...
